### ISSUE TITLE
MODE 2 version?

### ISSUE THREAD

**Issue by kieranhj** [tom-seddon/ghouls-tng#27]
Perhaps a bit too much work but wondering if MODE 2 might be an option for nicer gfx, depending on available RAM and cycles!

**Comment by tom-seddon** [comment]
I like this idea! As well as looking nicer on the stock Beeb, a properly nice NuLA version could be an option.

I think it wouldn't be too hard to get the game building to run in both Mode 2 and Mode 5. Copy twice as many sprite bytes, note that there's 640 bytes per line, and note that 1/40th the screen width is now 32 bytes. Cycles could be a problem, but in the standard levels there's loads of time left, so hopefully just a question of testing in the Mode 2 version. We know the Mode 5 version will work then.

(One thing that needs some consideration: the collision detection works by peeking screen RAM and looking for specific values. This might need adjusting as in Mode 2, since there's only 2 pixels/byte, and so checking 1 byte might not be enough to distinguish some types of object. (I think we should avoid trying to make this easy by doing anything clever with palette indexes or whatever, as that'll make the graphics for a NuLA reskin harder to create.)

RAM will be an issue in Mode 2. Even with PAGE at $e00, the BASIC code runs up to nearly $3000 already, and it still needs room for level data and code/sprites. Some ideas:

* convert BASIC into machine code, see if it all fits on a stock B - we would get a lot more zero page if doing this, if we need it, plus more importantly another 1 KB at $400...$7ff. It'd surely be a bit of a squeeze though!
* convert BASIC into machine code, require 1 bank sideways RAM - we wouldn't need to convert all the BASIC code in this case, just enough to get it to fit in Mode 2 assuming PAGE=&1100
* require B+ or Master 128, run BASIC part in shadow Mode 2, so HIMEM isn't an issue. Then <<insert details here>> to make it work. On M128, fiddle with ACCCON so the game access the displayed RAM. On B+, put the sprite drawing code in the special sideways RAM area that can access to the displayed RAM even when the shadow RAM is paged in.
